OutDir = He_only

executable   = run_wrapper_He_only.sh
arguments = $(Energy) $(OutDir)

output       = Simulations/$(OutDir)/job.$(ClusterId).$(ProcId).out
error        = Simulations/$(OutDir)/job.$(ClusterId).$(ProcId).err
log          = Simulations/$(OutDir)/job.$(ClusterId).$(ProcId).log

request_cpus   = 1
request_memory = 4GB
+JobFlavour    = "microcentury"
max_retries    = 3

queue Energy in (1 2 3 4 5 6 7 8 9 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100)
