OutDir = He_PVC

executable   = run_wrapper_He_only.sh
arguments = $(Energy) $(OutDir)

output       = Simulations/$(OutDir)/job.$(ClusterId).$(ProcId).out
error        = Simulations/$(OutDir)/job.$(ClusterId).$(ProcId).err
log          = Simulations/$(OutDir)/job.$(ClusterId).$(ProcId).log

request_cpus   = 1
request_memory = 4GB
+JobFlavour    = "microcentury"
max_retries    = 3

queue Energy in (1 2 3 4 6)
