OutDir = PVC

executable   = run_wrapper_SBT.sh
arguments = $(Energy) $(OutDir)

output       = Simulations/$(OutDir)/job.$(ClusterId).$(ProcId).out
error        = Simulations/$(OutDir)/job.$(ClusterId).$(ProcId).err
log          = Simulations/$(OutDir)/job.$(ClusterId).$(ProcId).log

request_cpus   = 1
request_memory = 4GB
+JobFlavour    = "microcentury"
max_retries    = 3

queue Energy in (1 2 3 4 5 6 7 8 9 10 20 40 60 80 100)
